version: '3.6'

services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=participants
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery.sh
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - redis
    depends_on:
      - redis
  monitor:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
      - 5555:5555
    depends_on:
      - redis
    links:
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_web.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=flasky.py
      - FLASK_ENV=development
#      - DATABASE_URL=mysql://user:password@db:3306/participants
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - worker
    links:
      - db
      - redis
      - worker
volumes:
  db:
    external: false
  redis:
    external: false