"""empty message

Revision ID: 279a9ad21951
Revises: 
Create Date: 2018-12-27 05:08:41.719476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279a9ad21951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbtype', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('hostname', sa.String(length=80), nullable=False),
    sa.Column('dbname', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    op.drop_table('message')
    op.drop_table('databases')
    # ### end Alembic commands ###
