"""empty message

Revision ID: 85f47e2b8489
Revises: 
Create Date: 2019-01-08 15:33:23.862806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f47e2b8489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbtype', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('hostname', sa.String(length=80), nullable=False),
    sa.Column('dbname', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed'), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=80), nullable=False),
    sa.Column('column_type', sa.String(length=80), nullable=False),
    sa.Column('column_default', sa.String(length=80), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('is_autoincrement', sa.Boolean(), nullable=False),
    sa.Column('is_pk', sa.Boolean(), nullable=False),
    sa.Column('is_fk', sa.Boolean(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreign_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('referred_column_id', sa.Integer(), nullable=True),
    sa.Column('referred_table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['referred_column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['referred_table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foreign_keys')
    op.drop_table('columns')
    op.drop_table('tables')
    op.drop_table('message')
    op.drop_table('databases')
    # ### end Alembic commands ###
